[getIPs]
# Oracle Cloud public IP ranges source
url = https://docs.oracle.com/en-us/iaas/tools/public_ip_ranges.json
output_file = result/ips.csv

[cfSpeedTest]
file_ips = result/ips.csv
max_ips = 48
max_ping = 896
test_size = 10240
min_download_speed = 20.0
min_upload_speed = 20.0
output_file = result/tested-ips.csv

[mapDomain]
ip_csv = result/ips.csv
input_csv = result/tested-ips.csv
output_csv = result/domains-ips.csv

[mapDomain.map]
# Region        = domain,max ip
Europe        = proxy.farel.is-a.dev,5
Middle_East   = proxy.farel.is-a.dev,5
Africa        = proxy.farel.is-a.dev,5
North_America = proxy.farel.is-a.dev,5
South_America = proxy.farel.is-a.dev,5
Asia          = proxy.farel.is-a.dev,5
Asia_Pacific  = proxy.farel.is-a.dev,5
Oceania       = proxy.farel.is-a.dev,5

[cfRecUpdate]
input_csv = result/domains-ips.csv
zone_id = 28ff747d0934fa1253d4423485da0345
